// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB2QkSHuJ0J9Ko_HJQMSh5426vo4YJCt0',
    appId: '1:72584110053:android:f8730c6d6097aebfb1990c',
    messagingSenderId: '72584110053',
    projectId: 'fir-project-d657c',
    databaseURL: 'https://fir-project-d657c-default-rtdb.firebaseio.com',
    storageBucket: 'fir-project-d657c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAa3r1ILgk2j6-80WEd8GvSVZHSMGHWGE',
    appId: '1:72584110053:ios:d139166021870d7db1990c',
    messagingSenderId: '72584110053',
    projectId: 'fir-project-d657c',
    databaseURL: 'https://fir-project-d657c-default-rtdb.firebaseio.com',
    storageBucket: 'fir-project-d657c.appspot.com',
    androidClientId: '72584110053-m354d19uq2un6g6m0v80f7din7nrru7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.allFirebase',
  );
}
